type Company {
    id: ID!
    name: String!
}

type Query {
    companies: [Company]!
} 

type Mutation {
    createCompany(name: String!): Company!
}

type Subscription {
    companyAdded: Company!
}